name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.prepare.outputs.tag }}
    strategy:
      fail-fast: false
      matrix:
        branch:
          - openwrt-24.10
        arch:
          - mediatek_filogic
          - mediatek_mt7622
    container:
      image: openwrt/sdk:${{ matrix.arch }}-${{ matrix.branch }}
      options: --user root
    defaults: { run: { shell: bash } }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SDK
        if: matrix.branch == 'openwrt-23.05' || matrix.branch == 'openwrt-24.10' || matrix.branch == 'SNAPSHOT'
        working-directory: /builder
        run: HOME=/builder ./setup.sh

      - name: Prepare build
        id: prepare
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: 'hufrea/byedpi'
        run : |
          TAG=$(wget -qO- --header="Authorization: token $GH_TOKEN" http://api.github.com/repos/$REPO/releases/latest | grep -Po '"tag_name": "\K.+?(?=")')
          sed "s|@VERSION@|${TAG#v}|" -i byedpi/Makefile
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build package
        id: build
        working-directory: ${{ matrix.branch == 'openwrt-19.07' && '/home/build/openwrt' || '/builder' }}
        env:
          ARCH: ${{ matrix.arch }}
          BRANCH: ${{ matrix.branch }}
          SIGN_KEY: ${{ secrets.SIGN_PRIVATE_KEY }}
        run: |
          echo "src-link byedpi $GITHUB_WORKSPACE" >> feeds.conf
          ./scripts/feeds update byedpi
          ./scripts/feeds install -a -p byedpi
          make defconfig
          make package/byedpi/compile V=s -j$(nproc) BUILD_LOG=1
          echo "$SIGN_KEY" | base64 -d > key-build
          make package/index
          tar -C ./bin/packages/*/byedpi -cvf $GITHUB_WORKSPACE/ipk-$BRANCH-$ARCH.tar --transform "s|^\./|${BRANCH/openwrt-}/$ARCH/|" --show-transformed-names .

      - name: Compress build logs
        if: always()
        env:
          ARCH: ${{ matrix.arch }}
          BRANCH: ${{ matrix.branch }}
          LOGS_DIR: ${{ matrix.branch == 'openwrt-19.07' && '/home/build/openwrt/logs' || '/builder/logs' }}
        run: |
          tar -cJvf logs-$BRANCH-$ARCH.tar.xz $LOGS_DIR

      - name: Upload packages
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: ipk-${{ matrix.branch }}-${{ matrix.arch }}
          path: ipk-${{ matrix.branch }}-${{ matrix.arch }}.tar
          if-no-files-found: error

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.branch }}-${{ matrix.arch }}
          path: logs-*.tar.xz

  gh-pages:
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ipk-*

      - name: Prepare files
        run: |
          mkdir public
          find . -name 'ipk-*.tar' -exec tar -C ./public -xvf {} \;
          cat <<EOF >> public/public.key
          untrusted comment: ByeDPI OpenWrt repo
          RWRT/Cfg5ReIbqWME8QTUQ1FKxp8FTr9M9g1vDsL8uIdRyP5TTNAk4QA
          EOF

      - name: Deploy to GH pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          full_commit_message: 'ByeDPI ${{ needs.build.outputs.tag }}'
          force_orphan: true

  release:
    needs: [ build, gh-pages ]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        branch:
          - '19.07'
          - '21.02'
          - '22.03'
          - '23.05'
          - '24.10'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ipk-*

      - name: Prepare files
        env:
          BRANCH: ${{ matrix.branch }}
        run: |
          find . -name "ipk-openwrt-$BRANCH-*.tar" -exec tar -xvf {} --wildcards '*.ipk' \;

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          tag_name: ${{ needs.build.outputs.tag }}-${{ matrix.branch }}
          name: ${{ needs.build.outputs.tag }} for OpenWrt ${{ matrix.branch }}
          target_commitish: gh-pages
          body: |
            ### ByeDPI ${{ needs.build.outputs.tag }} for OpenWrt ${{ matrix.branch }}

            -----
            Check the package architecture of your device using the command:
            ```
            # awk -F\' '/DISTRIB_ARCH/ {print $2}' /etc/openwrt_release
            ```
          files: ./**/*.ipk
